$(document).ready(function(){
  $('#inlineRadio1').click(function(){
    $('#gongin').removeClass('disnone');
    $('#personal').addClass('disnone');
  });
  $('#inlineRadio2').click(function(){
    $('#gongin').addClass('disnone');
    $('#personal').removeClass('disnone');
  });
  $('#inlineRadio3').click(function(){
    $('#gongin').addClass('disnone');
    $('#personal').removeClass('disnone');
  });

  $('.share1').click(function(){
    $('.new2').addClass('display-none');
    $('.new1').removeClass('display-none');
  });
  $('.share2').click(function(){
    $('.new1').addClass('display-none');
    $('.new2').removeClass('display-none');
  });
});
